// Code generated by Kitex v0.4.4. DO NOT EDIT.
package feedservice

import (
	feed "github.com/AgSword/simpleDouyin/kitex_gen/feed"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler feed.FeedService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	//println("NewServer这一步")
	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
