// Code generated by Kitex v0.4.4. DO NOT EDIT.

package favorite

import (
	"context"
	favorite "github.com/AgSword/simpleDouyin/kitex_gen/favorite"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return favoriteServiceInfo
}

var favoriteServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Favorite"
	handlerType := (*favorite.Favorite)(nil)
	methods := map[string]kitex.MethodInfo{
		"Action": kitex.NewMethodInfo(actionHandler, newFavoriteActionArgs, newFavoriteActionResult, false),
		"List":   kitex.NewMethodInfo(listHandler, newFavoriteListArgs, newFavoriteListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "favorite",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func actionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteActionArgs)
	realResult := result.(*favorite.FavoriteActionResult)
	success, err := handler.(favorite.Favorite).Action(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteActionArgs() interface{} {
	return favorite.NewFavoriteActionArgs()
}

func newFavoriteActionResult() interface{} {
	return favorite.NewFavoriteActionResult()
}

func listHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteListArgs)
	realResult := result.(*favorite.FavoriteListResult)
	success, err := handler.(favorite.Favorite).List(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteListArgs() interface{} {
	return favorite.NewFavoriteListArgs()
}

func newFavoriteListResult() interface{} {
	return favorite.NewFavoriteListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Action(ctx context.Context, req *favorite.DouyinFavoriteActionRequest) (r *favorite.DouyinFavoriteActionResponse, err error) {
	var _args favorite.FavoriteActionArgs
	_args.Req = req
	var _result favorite.FavoriteActionResult
	if err = p.c.Call(ctx, "Action", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) List(ctx context.Context, req *favorite.DouyinFavoriteListRequest) (r *favorite.DouyinFavoriteListResponse, err error) {
	var _args favorite.FavoriteListArgs
	_args.Req = req
	var _result favorite.FavoriteListResult
	if err = p.c.Call(ctx, "List", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
